from enum import StrEnum

PAGINATE_BY = 12


class ProjectStatus(StrEnum):
    OPEN = 'open'
    CLOSED = 'closed'


PROJECT_STATUS_CHOICES = [
    (ProjectStatus.OPEN, 'Open'),
    (ProjectStatus.CLOSED, 'Closed'),
]

PROJECT_NAME_MAX_LENGTH = 200

USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

AVATAR_SIZE = 200
AVATAR_FONT_SIZE = int(AVATAR_SIZE * 0.5)  

COLOR_RED = '#F44336'
COLOR_PINK = '#E91E63'
COLOR_PURPLE = '#9C27B0'
COLOR_DEEP_PURPLE = '#673AB7'
COLOR_INDIGO = '#3F51B5'
COLOR_BLUE = '#2196F3'
COLOR_TEAL = '#009688'
COLOR_GREEN = '#4CAF50'
COLOR_ORANGE = '#FF9800'
COLOR_BROWN = '#795548'

AVATAR_COLORS = [
    COLOR_RED,
    COLOR_PINK,
    COLOR_PURPLE,
    COLOR_DEEP_PURPLE,
    COLOR_INDIGO,
    COLOR_BLUE,
    COLOR_TEAL,
    COLOR_GREEN,
    COLOR_ORANGE,
    COLOR_BROWN,
]
